version: '3.8'

services:
    db:
        image: postgres:latest
        container_name: sentdebot-db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        restart: on-failure
    bot:
        build: .
        container_name: sentdebot
        volumes:
            -   .:/sentdebot/
        depends_on:
            - db
        restart: on-failure
    adminer:
        image: adminer
        container_name: sentdebot-adminer
        ports:
            - "8080:8080"
        depends_on:
            - db
        restart: on-failure

volumes:
    postgres_data:
