version: '3.8'

services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
    bot:
        build: .
        volumes:
            -   code_data:/sentdebot/
        depends_on:
            - db

volumes:
    postgres_data:
    code_data:
