version: '3.8'

services:
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
    bot:
        build: .
        volumes:
            -   ./:/sentdebot/
        depends_on:
            - db
    adminer:
        image: adminer
        ports:
            - "8080:8080"
        depends_on:
            - db

volumes:
    postgres_data:
