# <env> means this will be loaded from os environment variable with name <section>_<key>
# for example: "base_discord_api_key" for discord api key
# Ids should be unset by setting them to -1 but some may be required

[base]
discord_api_key = "<env>"
command_prefixes = ["?"]
status_message = "Sentdebot V2"

database_connect_string = "<env>"

# If true warning and error logs will also be logged in file discord.log
log_to_file = false

# Duration of error and success messages
error_duration = 30
success_duration = 30


[ids]
main_guild_id = 988202173152260176
# Channel that count as help channel
help_channel_id = 988498939818934272
# Control role ids
admin_role_ids = []
mod_role_ids = []
# Channle id to which error messages will be send
log_channel_id = 838455904571621427

[cogs]
# Cogs that will be loaded on startup and unable to be unloaded
protected_cogs = ["system", "errors", "help"]
# Cogs automatically loaded after start
defaul_loaded_cogs = ["common", "code_execute", "projects", "random_role_giver", "stats", "help_threader"]

[random_role_giver]
# Ids of roles that will be randomly given to users
role_ids = [988796853757812786, 988796949467627520, 988796952319758356, 988796951300571146]
chance = 0.2 # Chance on message to receive role in percents

[stats]
days_back = 21