# <env> means this will be loaded from os environment variable with name <section>_<key>
# for example: "base_discord_api_key" for discord api key

[base]
discord_api_key = "<env>"
command_prefixes = ["!"]
status_message = "Sentdebot V2"

# If true warning and error logs will also be logged in file discord.log
log_to_file = true
# Channle id to which error messages will be send
log_channel_id = -1

# Duration of error and success messages
error_duration = 30
success_duration = 30

[ids]
# Control role ids, -1 means unset
admin_role_id = -1
mod_role_id = -1

[cogs]
# Cogs that will be loaded on startup and unable to be unloaded
protected_cogs = ["system", "errors", "help"]