# Ids should be unset by setting them to -1 but some may be required

[base]
discord_api_key = ""
command_prefix = "!"
status_message = "Some status message"

# If true warning and error logs will also be logged in file discord.log
log_to_file = false

# Duration of error and success messages
error_duration = 30
success_duration = 30


[db]
# Connection string to database with specified engine
# This address is for usage with docker deployment
connect_string = "postgresql://postgres:postgres@db:5432/postgres" # Example for testing: "sqlite://database.db" For docker workflow: "postgresql://postgres:postgres@db:5432/postgres"


[ids]
main_guild = 988202173152260176
# Channel that count as help channel
help_channel = 988498939818934272
# Control role ids
admin_role = []
mod_role = []
# Channle id to which error messages will be send
log_channel = 838455904571621427
warden_channels_to_look_for = []
warden_report_channel = -1
warden_whitelisted_users = []


[cogs]
# Cogs that will be loaded on startup and unable to be unloaded
protected = ["system", "errors", "help", "listeners", "auditlog", "admin_tools"]
# Cogs automatically loaded after start
defaul_loaded = ["common", "code_execute", "projects", "weather", "random_role_giver", "stats", "help_threader", "bookmarks", "vc_notifier", "auto_help", "warden"]


[random_role_giver]
# Ids of roles that will be randomly given to users
role_ids = [988796853757812786, 988796949467627520, 988796952319758356, 988796951300571146]
chance = 0.2 # Chance on message to receive role in percents


[stats]
days_back = 21
name_length_limit = 18
max_graph_minutes_age_for_regenerate = 20
graph_bg_color_code = "#2F3136"


[help_threader]
close_request_after_days_of_inactivity = 10


[essentials]
max_cached_messages = 5000

# Disable by setting to -1
delete_left_users_after_days = 2
delete_messages_after_days = 60
delete_audit_logs_after_days = 60


[common]
vote_duration_seconds = 180


[voice_channel_notifier]
update_every_minutes = 0.5
stay_threshold_minutes = 2
delay_between_announcements_minutes = 15

vc_channel_ids = [991016207777943622, 999134772565643425]

[[voice_channel_notifier.notification_settings]]
user_threshold = 1
announce_role_id = 999132413206724668
announce_channel_id = 999125170260283444

[[voice_channel_notifier.notification_settings]]
user_threshold = 2
announce_role_id = 999135017341030410
announce_channel_id = 999134821458645062


[questions_and_answers]
# In percent
score_limit = 40


[warden]
message_cache_size = 500
expire_time_minutes = 5
strikes_to_notify = 2
decrement_strikes_every_minutes = 10

medium_similarity = 90
high_similarity = 95